baseURL = "https://willianpaixao.github.io"
languageCode = "en-us"
author = "Willian Paixao"
title = "Willian Paixao"
theme = "hugo-goa"

[params]
  author = "Willian Paixao"
  dateformat = "Mon Jan 2, 2006"
  intro = "DevOps Engineer at Ellmount"
  description = "Stockholm, Sweden"
  authorimage = "headshot.jpg"

[params.meta]
  description = "Willian Paixao - DevOps, SysAdmin, Developer"
  keywords = "willian,paixao,devops,engineer,sysadmin,linux"

[params.social]
  github = "willianpaixao"
  instagram = "willianpaixaoo"
  linkedin = "willianpaixao"
  twitter = "willianpaixaoo"
  email = "willian@ufpa.br"

[[menu.main]]
  name = "blog"
  weight = 100
  url = "/blog/"
[[menu.main]]
  name = "about"
  weight = 200
  url = "/about/"
[[menu.main]]
  name = "impossible list"
  weight = 200
  url = "/impossible-list/"
